CS_ORDERS = [{"small_private_customer"=>
   {:line_items=>
     [["wick/eco-2", 2],
      ["molds/3x3-Round-Pillar-Mold-Concave-Top", 1],
      ["molds/flaired-votive-candle-mold", 1],
      ["equipment/votive-wick-pin", 1],
      ["fragrance/very-vanilla-fragrance-oil", 1]],
    :state_id=>46,
    :zip=>"02346"}},
 {"small_fragrence_only"=>
   {:line_items=>
     [["fragrance/apple-harvest-fragrance-oil", 1],
      ["fragrance/nag-champa-fragrance-oil", 1],
      ["fragrance/dragons-blood-fragrance-oil", 1],
      ["fragrance/cinnamon-buns-fragrance-oil", 1],
      ["fragrance/rain-water-fragrance-oil", 1]],
    :state_id=>42,
    :zip=>"41001"}},
 {"small_equipment_with_items"=>
   {:line_items=>
     [["color/black-liquid-dye", 1],
      ["color/blue-liquid-dye", 1],
      ["equipment/1inch-labels", 1],
      ["fragrance/peach-fragrance-oil", 1],
      ["fragrance/macintosh-apple-fragrance-oil", 1]],
    :state_id=>49,
    :zip=>"29607"}},
 {"small_wick_and_fragrence"=>
   {:line_items=>
     [["wick/eco-4", 1],
      ["wick/eco-10", 1],
      ["fragrance/love-spell-fragrance-oil", 1],
      ["fragrance/strawberry-shortcake-fragrance-oil", 1],
      ["fragrance/lavender-chamomile-fragrance-oil", 1]],
    :state_id=>29,
    :zip=>"56074"}},
 {"small_fragrence_with_labels"=>
   {:line_items=>
     [["fragrance/driftwood-fragrance-oil", 1],
      ["fragrance/sweet-pea-fragrance-oil", 1],
      ["fragrance/cotton-tree-fragrance-oil", 1],
      ["equipment/1inch-labels", 1],
      ["fragrance/smoke-and-odor-fragrance-oil", 1],
      ["fragrance/cool-citrus-basil-fragrance-oil", 1],
      ["fragrance/grapefruit-and-mangosteen-fragrance-oil", 1]],
    :state_id=>48,
    :zip=>"11746"}},
 {"medium_fragrence_with_labels"=>
   {:line_items=>
     [["containers/straight-sided-tumbler-jar-amber", 2],
      ["containers/8oz-mason-jar-label-ready", 6],
      ["wax/golden-brands-464-soy-wax", 1],
      ["fragrance/caribbean-teakwood-fragrance-oil", 1],
      ["fragrance/lemon-verbena-fragrance-oil", 1],
      ["fragrance/apple-harvest-fragrance-oil", 1],
      ["fragrance/cinnamon-chai-fragrance-oil", 1],
      ["fragrance/fruit-slices-fragrance-oil", 1],
      ["fragrance/grapefruit-and-mangosteen-fragrance-oil", 1],
      ["equipment/1inch-labels", 1],
      ["containers/gold-jelly-lid", 6]],
    :state_id=>44,
    :zip=>"30087"}},
 {"medium_jars_and_oils"=>
   {:line_items=>
     [["containers/3oz-tureen-jar", 2],
      ["containers/70-gold-twist-top", 1],
      ["containers/6oz-tureen-jar", 2],
      ["containers/82-silver-twist-top", 1],
      ["wick/eco-12", 1],
      ["wax/golden-brands-444-soy-wax", 1],
      ["equipment/wick-stickums-large", 2],
      ["equipment/wick-bar", 2],
      ["fragrance/macintosh-apple-fragrance-oil", 1],
      ["fragrance/strawberry-shortcake-fragrance-oil", 1],
      ["fragrance/rain-water-fragrance-oil", 1],
      ["wick/eco-10", 1]],
    :state_id=>26,
    :zip=>"21136"}},
 {"medium_varied_order"=>
   {:line_items=>
     [["containers/8oz-oval-hex-jar", 10],
      ["wax/ecosoya-advanced-soy-wax", 1],
      ["containers/63-gold-twist-top", 1],
      ["wick/lx-24", 1],
      ["wick/lx-26", 1],
      ["fragrance/christmas-hearth-fragrance-oil", 1],
      ["fragrance/angel-type-fragrance-oil", 1],
      ["fragrance/lavender-chamomile-fragrance-oil", 1],
      ["fragrance/cassia-and-amber-fragrance-oil", 1],
      ["fragrance/english-garden-fragrance-oil", 1],
      ["fragrance/lavender-chamomile-fragrance-oil", 1],
      ["containers/medium-lucida-jar", 2],
      ["equipment/1inch-labels", 1]],
    :state_id=>48,
    :zip=>"11377"}},
 {"medium_size_medium_quantities"=>
   {:line_items=>
     [["containers/straight-sided-tumbler-jar-black", 6],
      ["containers/4oz-squat-hex-jar", 4],
      ["packaging/white-straight-sided-tumbler-box", 6],
      ["fragrance/black-currant-tea-fragrance-oil", 1],
      ["containers/6oz-tureen-jar", 4],
      ["containers/82-gold-twist-top", 4],
      ["containers/58-gold-twist-top", 4],
      ["fragrance/plumeria-fragrance-oil", 1],
      ["fragrance/ocean-breeze-fragrance-oil", 1],
      ["containers/2oz-status-jar", 2],
      ["equipment/wax-melt-warning-labels", 1],
      ["equipment/1inch-labels", 1],
      ["containers/wax-melt-clamshell", 5]],
    :state_id=>48,
    :zip=>"12047"}},
 {"medium_size_small_quantity"=>
   {:line_items=>
     [["fragrance/honeysuckle-jasmine-fragrance-oil", 1],
      ["fragrance/mint-mojito-fragrance-oil", 1],
      ["fragrance/gardenia-fragrance-oil", 1],
      ["fragrance/peach-nectar-fragrance-oil", 1],
      ["containers/straight-sided-tumbler-jar-white", 2],
      ["fragrance/black-cherry-fragrance-oil", 1],
      ["fragrance/blood-orange-fragrance-oil", 1],
      ["fragrance/amber-noir-fragrance-oil", 1],
      ["wick/eco-14", 1],
      ["fragrance/blueberry-cheesecake-fragrance-oil", 1],
      ["fragrance/mango-papaya-fragrance-oil", 1],
      ["packaging/white-tumbler-box", 2],
      ["fragrance/vanilla-hazelnut-fragrance-oil", 1],
      ["wax/golden-brands-464-soy-wax", 1]],
    :state_id=>48,
    :zip=>"11433"}},
 {"medium_size_varied_items"=>
   {:line_items=>
     [["containers/medium-straight-sided-jar", 4],
      ["containers/70-gold-twist-top", 4],
      ["wax/igi-4630", 4],
      ["containers/8oz-mason-jar-label-ready", 3],
      ["containers/rustic-jelly-lid", 3],
      ["containers/8oz-tureen-jar", 2],
      ["containers/82-gold-twist-top", 2],
      ["wick/lx-18", 1],
      ["wick/htp-83", 1],
      ["color/yellow-liquid-dye", 1],
      ["fragrance/banana-nut-bread-fragrance-oil", 1],
      ["fragrance/very-vanilla-fragrance-oil", 1],
      ["fragrance/honeydew-melon-fragrance-oil", 1],
      ["fragrance/apple-jack-peel-fragrance-oil", 1]],
    :state_id=>28,
    :zip=>"23920"}},
 {"medium_wicks_and_fragrence"=>
   {:line_items=>
     [["wick/lx-14", 2],
      ["wick/lx-16", 2],
      ["wick/lx-20", 2],
      ["equipment/ez-wick-setter-multi", 1],
      ["wick/lx-24", 1],
      ["wick/lx-18", 1],
      ["fragrance/amber-noir-fragrance-oil", 1],
      ["equipment/wick-stickums-large", 2],
      ["equipment/2inch-labels", 2],
      ["fragrance/apple-harvest-fragrance-oil", 1],
      ["fragrance/black-sea-fragrance-oil", 1],
      ["fragrance/cotton-tree-fragrance-oil", 1],
      ["fragrance/rose-fragrance-oil", 1],
      ["fragrance/love-spell-fragrance-oil", 1]],
    :state_id=>6,
    :zip=>"60643"}},
 {"medium_wax_and_fragrence"=>
   {:line_items=>
     [["fragrance/amber-noir-fragrance-oil", 1],
      ["fragrance/driftwood-fragrance-oil", 1],
      ["containers/12-cube-jar", 1],
      ["fragrance/lemon-pound-cake-fragrance-oil", 1],
      ["fragrance/pomegranate-fragrance-oil", 1],
      ["wick/eco-6", 1],
      ["wick/eco-12", 1],
      ["wax/ecosoya-advanced-soy-wax", 1],
      ["wax/golden-brands-415-soy-wax", 1],
      ["wick/eco-16", 1],
      ["wax/golden-brands-464-soy-wax", 1],
      ["containers/classic-tumbler-jar", 1],
      ["wick/eco-14", 1],
      ["fragrance/banana-nut-bread-fragrance-oil", 1]],
    :state_id=>11,
    :zip=>"72802"}},
 {"medium_fragrence_with_containers"=>
   {:line_items=>
     [["wax/golden-brands-464-soy-wax", 1],
      ["wick/eco-10", 1],
      ["fragrance/clean-cotton-fragrance-oil", 1],
      ["fragrance/lemon-pound-cake-fragrance-oil", 1],
      ["fragrance/angel-type-fragrance-oil", 1],
      ["fragrance/gardenia-fragrance-oil", 1],
      ["fragrance/black-sea-fragrance-oil", 1],
      ["fragrance/black-cherry-fragrance-oil", 1],
      ["fragrance/smoke-and-odor-fragrance-oil", 1],
      ["fragrance/sunwashed-linen-fragrance-oil", 1],
      ["fragrance/sunwashed-linen-fragrance-oil", 1],
      ["containers/12oz-oval-hex-jar", 1],
      ["containers/63-silver-twist-top", 1],
      ["containers/6oz-hex-jar", 1],
      ["containers/58-silver-twist-top", 1]],
    :state_id=>8,
    :zip=>"27540"}},
 {"medium_dyes_and_fragrences"=>
   {:line_items=>
     [["fragrance/christmas-hearth-fragrance-oil", 2],
      ["fragrance/hansel-gretels-house-fragrance-oil", 2],
      ["fragrance/peppermint-bark-fragrance-oil", 2],
      ["color/ivory-liquid-dye", 1],
      ["color/christmas-green-dye-chips", 2],
      ["equipment/1inch-labels", 1],
      ["equipment/2inch-labels", 2],
      ["color/brown-liquid-dye", 1],
      ["fragrance/mistletoe-fragrance-oil", 2],
      ["fragrance/gingerbread-fragrance-oil", 2],
      ["fragrance/brandied-pear-fragrance-oil", 2],
      ["wick/htp-83", 2],
      ["wax/igi-4627", 1],
      ["fragrance/cinnamon-chai-fragrance-oil", 1],
      ["fragrance/banana-nut-bread-fragrance-oil", 1]],
    :state_id=>28,
    :zip=>"23139"}},
 {"medium_fragrence_with_equipment"=>
   {:line_items=>
     [["fragrance/chocolate-fudge-fragrance-oil", 1],
      ["fragrance/cinnamon-buns-fragrance-oil", 1],
      ["fragrance/day-at-the-spa-fragrance-oil", 1],
      ["fragrance/fresh-coffee-fragrance-oil", 1],
      ["fragrance/gingerbread-fragrance-oil", 1],
      ["fragrance/lavender-fragrance-oil", 1],
      ["fragrance/mistletoe-fragrance-oil", 1],
      ["fragrance/mulled-cider-and-chestnuts-fragrance-oil", 1],
      ["fragrance/peppermint-bark-fragrance-oil", 1],
      ["fragrance/raspberry-sangria-fragrance-oil", 1],
      ["containers/8oz-candle-tin", 2],
      ["wax/golden-brands-415-soy-wax", 2],
      ["equipment/wick-bar", 1],
      ["equipment/1inch-labels", 1],
      ["equipment/wick-stickums-large", 1],
      ["wick/eco-12", 1]],
    :state_id=>31,
    :zip=>"44021"}},
 {"medium_with_glass_thermometer"=>
   {:line_items=>
     [["wax/golden-brands-464-soy-wax", 1],
      ["fragrance/cake-fragrance-oil", 1],
      ["fragrance/cedarwood-vanilla-fragrance-oil", 1],
      ["fragrance/cinnamon-buns-fragrance-oil", 1],
      ["fragrance/lemon-pound-cake-fragrance-oil", 1],
      ["fragrance/lavender-cucumber-sage-fragrance-oil", 1],
      ["color/gold-dye-chips", 2],
      ["color/aqua-marine-dye-chips", 1],
      ["color/lavender-dye-chips", 1],
      ["color/ivory-dye-chips", 2],
      ["equipment/wick-stickums-large", 1],
      ["equipment/wick-bar", 2],
      ["equipment/glass-thermometer", 2],
      ["equipment/small-pouring-pitcher", 4],
      ["wick/eco-10", 1],
      ["fragrance/chardonnay-fragrance-oil", 1]],
    :state_id=>26,
    :zip=>"20662"}},
 {"medium_flaired_votive_candle"=>
   {:line_items=>
     [["fragrance/chardonnay-fragrance-oil", 1],
      ["fragrance/apple-harvest-fragrance-oil", 1],
      ["fragrance/pumpkin-souffle-fragrance-oil", 1],
      ["containers/8oz-apothecary-jar", 1],
      ["containers/large-dome-top", 1],
      ["molds/flaired-votive-candle-mold", 1],
      ["color/orange-liquid-dye", 1],
      ["color/red-liquid-dye", 1],
      ["color/purple-liquid-dye", 1],
      ["wax/igi-4625", 1],
      ["wax/igi-4630", 1],
      ["wick/lx-12", 1],
      ["wick/lx-20", 1],
      ["equipment/1inch-labels", 1],
      ["equipment/2inch-labels", 1],
      ["fragrance/lemon-pound-cake-fragrance-oil", 1]],
    :state_id=>6,
    :zip=>"60143"}},
 {"medium_standard_order"=>
   {:line_items=>
     [["wick/eco-10", 1],
      ["wax/golden-brands-464-soy-wax", 1],
      ["containers/16oz-apothecary-jar", 1],
      ["containers/large-flat-top", 2],
      ["wick/eco-16", 1],
      ["containers/26oz-apothecary-jar", 1],
      ["fragrance/frankincense-and-myrrh-fragrance-oil", 1],
      ["color/canary-yellow-dye-blocks", 1],
      ["color/navy-blue-dye-blocks", 1],
      ["color/red-dye-blocks", 1],
      ["fragrance/honeysuckle-jasmine-fragrance-oil", 1],
      ["containers/8oz-candle-tin", 2],
      ["fragrance/mint-mojito-fragrance-oil", 1],
      ["equipment/1inch-labels", 1],
      ["equipment/2inch-labels", 1],
      ["fragrance/english-garden-fragrance-oil", 1],
      ["fragrance/egyptian-amber-fragrance-oil", 1]],
    :state_id=>26,
    :zip=>"21921"}},
 {"large_fragrence_and_colors"=>
   {:line_items=>
     [["fragrance/black-cherry-fragrance-oil", 1],
      ["fragrance/oakmoss-and-amber-fragrance-oil", 1],
      ["fragrance/english-garden-fragrance-oil", 1],
      ["color/yellow-liquid-dye", 1],
      ["color/red-liquid-dye", 1],
      ["color/blue-liquid-dye", 1],
      ["fragrance/apple-harvest-fragrance-oil", 1],
      ["fragrance/black-sea-fragrance-oil", 1],
      ["fragrance/cotton-tree-fragrance-oil", 1],
      ["fragrance/cucumber-melon-fragrance-oil", 1],
      ["fragrance/gardenia-fragrance-oil", 1],
      ["fragrance/grapefruit-and-mangosteen-fragrance-oil", 1],
      ["fragrance/mediterranean-fig-fragrance-oil", 1],
      ["fragrance/peach-fragrance-oil", 1],
      ["fragrance/rose-fragrance-oil", 1],
      ["fragrance/sweet-pea-fragrance-oil", 1],
      ["wick/eco-10", 1],
      ["equipment/1inch-labels", 1],
      ["wax/golden-brands-444-soy-wax", 1]],
    :state_id=>48,
    :zip=>"11223"}},
 {"large_ensoya"=>
   {:line_items=>
     [["fragrance/black-raspberry-vanilla-type-fragrance-oil", 1],
      ["fragrance/caribbean-teakwood-fragrance-oil", 1],
      ["fragrance/coconut-lime-fragrance-oil", 1],
      ["fragrance/cucumber-melon-fragrance-oil", 1],
      ["fragrance/english-garden-fragrance-oil", 1],
      ["fragrance/grapefruit-and-mangosteen-fragrance-oil", 1],
      ["fragrance/hydrangea-fragrance-oil", 1],
      ["fragrance/jamaica-me-crazy-fragrance-oil", 1],
      ["fragrance/mango-tangerine-fragrance-oil", 1],
      ["fragrance/orange-chili-pepper-fragrance-oil", 1],
      ["fragrance/rain-water-fragrance-oil", 1],
      ["fragrance/smoke-and-odor-fragrance-oil", 1],
      ["fragrance/warm-vanilla-sugar-type-fragrance-oil", 1],
      ["wax/igi-6006", 1],
      ["wax/ecosoya-pillar-soy-wax", 1],
      ["containers/wax-melt-clamshell", 1],
      ["containers/8oz-mason-jar", 1],
      ["containers/pewter-jelly-lid", 1],
      ["wick/eco-2", 2]],
    :state_id=>8,
    :zip=>"28411"}},
 {"large_color_fragrenc"=>
   {:line_items=>
     [["fragrance/buttered-rum-fragrance-oil", 1],
      ["fragrance/red-hot-cinnamon-fragrance-oil", 1],
      ["fragrance/chardonnay-fragrance-oil", 1],
      ["fragrance/strawberry-shortcake-fragrance-oil", 1],
      ["fragrance/sex-on-the-beach-fragrance-oil", 2],
      ["fragrance/clean-cotton-fragrance-oil", 1],
      ["fragrance/garden-mint-fragrance-oil", 1],
      ["fragrance/blueberry-cheesecake-fragrance-oil", 1],
      ["fragrance/caramel-popcorn-fragrance-oil", 1],
      ["wick/eco-75-tealight", 1],
      ["containers/clear-plastic-tealight-cups", 1],
      ["color/navy-blue-dye-chips", 2],
      ["color/aqua-marine-dye-chips", 2],
      ["color/cinnamon-red-dye-chips", 2],
      ["color/pale-pink-dye-chips", 1],
      ["color/hunter-green-dye-chips", 1],
      ["wick/eco-4", 1],
      ["fragrance/black-currant-tea-fragrance-oil", 1],
      ["fragrance/black-sea-fragrance-oil", 1]],
    :state_id=>44,
    :zip=>"30553"}},
 {"large_all_one_quantity"=>
   {:line_items=>
     [["wick/eco-12", 1],
      ["wick/lx-wick-sample-kit", 1],
      ["wick/csn-wick-sample-kit", 1],
      ["equipment/wick-stickums-large", 1],
      ["equipment/2inch-labels", 1],
      ["wax/golden-brands-464-soy-wax", 1],
      ["fragrance/peach-nectar-fragrance-oil", 2],
      ["fragrance/caribbean-teakwood-fragrance-oil", 2],
      ["fragrance/grapefruit-and-mangosteen-fragrance-oil", 2],
      ["fragrance/jamaica-me-crazy-fragrance-oil", 2],
      ["fragrance/raspberry-sangria-fragrance-oil", 2],
      ["fragrance/meadow-fragrance-oil", 1],
      ["fragrance/lavender-chamomile-fragrance-oil", 1],
      ["fragrance/lavender-cucumber-sage-fragrance-oil", 1],
      ["fragrance/english-garden-fragrance-oil", 1],
      ["fragrance/oakmoss-and-amber-fragrance-oil", 1],
      ["fragrance/peach-fragrance-oil", 1],
      ["fragrance/rosemary-fragrance-oil", 1],
      ["fragrance/coconut-lime-fragrance-oil", 1],
      ["fragrance/mulberry-fragrance-oil", 1],
      ["fragrance/garden-mint-fragrance-oil", 1]],
    :state_id=>25,
    :zip=>"37129"}},
 {"large_with_labels"=>
   {:line_items=>
     [["wax/golden-brands-464-soy-wax", 1],
      ["wax/ecosoya-pillar-soy-wax", 1],
      ["containers/8oz-apothecary-jar", 1],
      ["containers/16oz-apothecary-jar", 1],
      ["containers/6oz-hex-jar", 1],
      ["containers/large-dome-top", 1],
      ["containers/large-flat-top", 1],
      ["containers/43-gold-twist-top", 1],
      ["containers/wax-melt-clamshell", 1],
      ["containers/clear-plastic-tealight-cups", 1],
      ["wick/eco-1-tealight", 1],
      ["wick/eco-1", 1],
      ["molds/flaired-votive-candle-mold", 1],
      ["molds/tart-mold", 1],
      ["color/aqua-marine-dye-chips", 1],
      ["color/cinnamon-red-dye-chips", 1],
      ["color/butterscotch-dye-chips", 1],
      ["color/pale-pink-dye-chips", 1],
      ["fragrance/baby-powder-fragrance-oil", 1],
      ["fragrance/banana-nut-bread-fragrance-oil", 1],
      ["fragrance/clean-cotton-fragrance-oil", 1],
      ["fragrance/lavender-fragrance-oil", 1],
      ["fragrance/cinnamon-stick-fragrance-oil", 1],
      ["fragrance/very-vanilla-fragrance-oil", 1],
      ["equipment/2inch-labels", 1]],
    :state_id=>27,
    :zip=>"33411"}},
 {"large_with_everything"=>
   {:line_items=>
     [["wax/ecosoya-pillar-soy-wax", 1],
      ["color/orange-liquid-dye", 1],
      ["color/yellow-liquid-dye", 1],
      ["color/red-liquid-dye", 1],
      ["fragrance/pumpkin-pie-fragrance-oil", 2],
      ["equipment/2inch-labels", 1],
      ["containers/medium-straight-sided-jar", 1],
      ["equipment/small-pouring-pitcher", 1],
      ["wax/igi-4625", 1],
      ["color/pale-pink-dye-chips", 1],
      ["fragrance/meadow-fragrance-oil", 1],
      ["molds/tart-mold", 1],
      ["wick/lx-12", 1],
      ["fragrance/banana-nut-bread-fragrance-oil", 1],
      ["fragrance/lilac-fragrance-oil", 1],
      ["fragrance/whiskey-fragrance-oil", 1],
      ["fragrance/driftwood-fragrance-oil", 1],
      ["fragrance/apples-maple-bourbon-fragrance-oil", 1],
      ["wick/csn-7", 1],
      ["containers/4oz-squat-hex-jar", 1],
      ["fragrance/plumeria-fragrance-oil", 1],
      ["molds/flaired-votive-candle-mold", 1],
      ["fragrance/christmas-hearth-fragrance-oil", 1],
      ["fragrance/hansel-gretels-house-fragrance-oil", 1],
      ["fragrance/christmas-tree-fragrance-oil", 1],
      ["fragrance/fresh-coffee-fragrance-oil", 1],
      ["fragrance/day-at-the-spa-fragrance-oil", 1],
      ["fragrance/drakkar-type-fragrance-oil", 1],
      ["fragrance/baby-powder-fragrance-oil", 1]],
    :state_id=>1,
    :zip=>"49630"}},
 {"large_with_mass_quantities"=>
   {:line_items=>
     [["containers/4oz-jelly-jar", 167],
      ["containers/8oz-jelly-jar", 1],
      ["wax/golden-brands-444-soy-wax", 46],
      ["wick/eco-10", 4],
      ["equipment/wick-stickums-small", 4],
      ["equipment/1inch-labels", 4],
      ["equipment/melter-65lb", 1],
      ["color/black-liquid-dye", 1],
      ["color/blue-liquid-dye", 1],
      ["color/brown-liquid-dye", 1],
      ["color/burgundy-liquid-dye", 1],
      ["color/golden-honey-liquid-dye", 1],
      ["color/hunter-green-liquid-dye", 1],
      ["color/ivory-liquid-dye", 1],
      ["color/magenta-liquid-dye", 1],
      ["color/orange-liquid-dye", 1],
      ["color/purple-liquid-dye", 1],
      ["color/red-liquid-dye", 1],
      ["color/summer-breeze-liquid-dye", 1],
      ["color/yellow-liquid-dye", 1],
      ["containers/rustic-jelly-lid", 4],
      ["fragrance/strudel-spice-fragrance-oil", 1],
      ["fragrance/apples-maple-bourbon-fragrance-oil", 1],
      ["fragrance/blueberry-cobbler-fragrance-oil", 1],
      ["fragrance/caramel-popcorn-fragrance-oil", 1],
      ["fragrance/cool-citrus-basil-fragrance-oil", 1],
      ["fragrance/creme-brulee-fragrance-oil", 1],
      ["fragrance/fresh-coffee-fragrance-oil", 1],
      ["fragrance/harvest-berry-fragrance-oil", 1],
      ["fragrance/island-coconut-fragrance-oil", 1],
      ["fragrance/lemon-pound-cake-fragrance-oil", 1],
      ["fragrance/mango-tangerine-fragrance-oil", 1],
      ["fragrance/peach-nectar-fragrance-oil", 1],
      ["fragrance/pecan-pie-fragrance-oil", 1],
      ["fragrance/pineapple-coconut-fragrance-oil", 5],
      ["fragrance/pumpkin-souffle-fragrance-oil", 1],
      ["fragrance/smoke-and-odor-fragrance-oil", 5],
      ["fragrance/amaretto-nog-fragrance-oil", 5],
      ["fragrance/mimosa-and-mandarin-fragrance-oil", 1]],
    :state_id=>51,
    :zip=>"25248"}},
 {"giant_with_medium_quantities"=>
   {:line_items=>
     [["containers/8oz-jelly-jar", 1],
      ["containers/12oz-canning-jar", 12],
      ["containers/16oz-canning-jar", 24],
      ["containers/12oz-status-jar", 12],
      ["containers/rustic-jelly-lid", 2],
      ["wick/eco-10", 2],
      ["wax/golden-brands-415-soy-wax", 10],
      ["wax/ecosoya-pillar-soy-wax", 10],
      ["wax/golden-brands-464-soy-wax", 13],
      ["color/brown-dye-blocks", 6],
      ["color/canary-yellow-dye-blocks", 6],
      ["color/forest-green-dye-blocks", 6],
      ["color/lavender-dye-blocks", 12],
      ["color/navy-blue-dye-blocks", 6],
      ["color/pink-dye-blocks", 6],
      ["color/pumpkin-dye-blocks", 6],
      ["color/red-dye-blocks", 6],
      ["fragrance/apple-harvest-fragrance-oil", 1],
      ["fragrance/banana-nut-bread-fragrance-oil", 1],
      ["fragrance/black-cherry-fragrance-oil", 3],
      ["fragrance/blueberry-cobbler-fragrance-oil", 1],
      ["fragrance/caramelized-pralines-fragrance-oil", 1],
      ["fragrance/cinnamon-buns-fragrance-oil", 1],
      ["fragrance/cinnamon-stick-fragrance-oil", 1],
      ["fragrance/cotton-candy-fragrance-oil", 1],
      ["fragrance/egyptian-amber-fragrance-oil", 1],
      ["fragrance/fresh-coffee-fragrance-oil", 1],
      ["fragrance/hansel-gretels-house-fragrance-oil", 1],
      ["fragrance/hazelnut-coffee-fragrance-oil", 1],
      ["fragrance/honeysuckle-fragrance-oil", 4],
      ["fragrance/jamaica-me-crazy-fragrance-oil", 1],
      ["fragrance/lilac-fragrance-oil", 1],
      ["fragrance/love-spell-fragrance-oil", 1],
      ["fragrance/oakmoss-and-amber-fragrance-oil", 1],
      ["fragrance/orange-and-goji-berry-fragrance-oil", 1],
      ["fragrance/pecan-pie-fragrance-oil", 1],
      ["fragrance/very-vanilla-fragrance-oil", 1],
      ["fragrance/beach-linen-fragrance-oil", 2],
      ["fragrance/caramel-popcorn-fragrance-oil", 2],
      ["fragrance/clean-cotton-fragrance-oil", 1],
      ["fragrance/cool-citrus-basil-fragrance-oil", 1],
      ["fragrance/cotton-tree-fragrance-oil", 2],
      ["fragrance/creme-brulee-fragrance-oil", 2],
      ["fragrance/english-garden-fragrance-oil", 1],
      ["fragrance/hydrangea-fragrance-oil", 1],
      ["fragrance/island-coconut-fragrance-oil", 2],
      ["fragrance/juniper-breeze-fragrance-oil", 1],
      ["fragrance/lavender-cucumber-sage-fragrance-oil", 1],
      ["fragrance/lemon-pound-cake-fragrance-oil", 1],
      ["fragrance/lemon-verbena-fragrance-oil", 2],
      ["fragrance/nag-champa-fragrance-oil", 2],
      ["fragrance/peach-nectar-fragrance-oil", 2],
      ["fragrance/pink-sugar-type-fragrance-oil", 1],
      ["fragrance/plumeria-fragrance-oil", 1],
      ["fragrance/smoke-and-odor-fragrance-oil", 2],
      ["fragrance/strawberry-shortcake-fragrance-oil", 2],
      ["containers/6oz-candle-tin", 1],
      ["fragrance/sunwashed-linen-fragrance-oil", 1]],
    :state_id=>16,
    :zip=>"15714"}}]
